---
- name: Create vth group info.
  group:
    name: '{{ hostname }}'
  become: yes

- name: Create user.
  user:
    name: '{{ hostname }}'
    group: '{{ hostname }}'
  become: yes

- name: Check docker install.
  package:
    name: docker
    state: present

# - include_tasks: setup.yml

# services

- name: Run the docker API images
  community.docker.docker_container:
    name: api
    # image: manhlab/vt_api
    image: manhlab/vt_webapp
    state: started
    # restart: true
    # ports:
    #   - "8081:8080"

    ports:
      - "4000:4000"
    env_file: "/home/minh/Downloads/learnAnsible/HWansible/roles/api/files/.env"
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    command: uvicorn main:app --reload --host 0.0.0.0 --port 4000