apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31108
  selector:
    app: react-nginx