version: '3'
services:
  appuser:
    build: ./app
    depends_on:
      - dbmongo
    ports:
      - 5000:5000
    networks:
      - db
      - app
    
    
  nginx-production:
    image: nginx:1.22.0-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - appuser
    networks:
      - app


  dbmongo:
    image: mongo:5.0 
    
    ports:
      - 27017:27017
    volumes:
      - db1:/data/db
    networks:
      - db
volumes:
  db1:

networks:
  db:
    driver: bridge
  app:
    driver: bridge
