---
- name: Create group info.
  group:
    name: vt
  become: yes

- name: Create user.
  user:
    name: vt
    group: vt
  become: yes

# svc

- name: Run the docker API images
  community.docker.docker_container:
    name: api
    image: manhlab/vt_api
    state: started
    # restart: true
    ports:
      - "8080:8080"
    # enenvironment:

    env_file: "/home/minh/Downloads/learnAnsible/HWansible/roles/api/files/.env"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080