apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata: 
      labels:
        app: mern-k8s
        component: back
    spec:
      containers:
        - name: mern-k8s-back
          image: trongminhjr/mern-k8s-back
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports: 
            - containerPort: 3000
          env: 
            - name: PORT
              value: "3000"
            - name: CONN_STR
              value: "mongodb://admin:admin@mongo:27017"