name: CI/CD

on:
  push:
    branches: [ "main", "GK" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unittest-backend-api:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./10.GK/PhamHongThanh/src/backend/requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Unit test
        run: |
          cd ./10.GK/PhamHongThanh/src/backend
          python -m unittest discover -s app -p 'test_*.py' -v
          
  build-and-push:
    name: Build and Push image to DockerHub
    runs-on: ubuntu-latest
    steps:   
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build and push Database Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:10.GK/PhamHongThanh/src/mongodb"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thanhph/mongodb:${{  github.ref_name }}
      - name: Build and push Database Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:10.GK/PhamHongThanh/src/backend"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thanhph/backend:${{  github.ref_name }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:10.GK/PhamHongThanh/src/frontend"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thanhph/frontend:${{  github.ref_name }}